/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();

        setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mCuenta = new javax.swing.JMenu();
        mCGestion = new javax.swing.JMenuItem();
        mCIngresar = new javax.swing.JMenuItem();
        mPartida = new javax.swing.JMenu();
        mPIngresar = new javax.swing.JMenuItem();
        mReportes = new javax.swing.JMenu();
        mRDiario = new javax.swing.JMenuItem();
        mRMayor = new javax.swing.JMenuItem();
        mRBalanza = new javax.swing.JMenuItem();
        mREstado = new javax.swing.JMenuItem();
        mRBalance = new javax.swing.JMenuItem();
        mEjercicio = new javax.swing.JMenu();
        mEApertura = new javax.swing.JMenuItem();
        mECierre = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();

        jMenuItem11.setText("jMenuItem11");

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/conti.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(5800, 3000));

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );

        mCuenta.setText("CUENTAS");
        mCuenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mCGestion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mCGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GESTION.png"))); // NOI18N
        mCGestion.setText("GESTION");
        mCGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCGestionActionPerformed(evt);
            }
        });
        mCuenta.add(mCGestion);

        mCIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mCIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AGREGAR.png"))); // NOI18N
        mCIngresar.setText("INGRESAR");
        mCIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCIngresarActionPerformed(evt);
            }
        });
        mCuenta.add(mCIngresar);

        jMenuBar1.add(mCuenta);

        mPartida.setText("PARTIDAS");
        mPartida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mPIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mPIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AGREGAR.png"))); // NOI18N
        mPIngresar.setText("INGRESAR");
        mPIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPIngresarActionPerformed(evt);
            }
        });
        mPartida.add(mPIngresar);

        jMenuBar1.add(mPartida);

        mReportes.setText("REPORTES");
        mReportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mRDiario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mRDiario.setText("LIBRO DIARIO");
        mReportes.add(mRDiario);

        mRMayor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mRMayor.setText("LIBRO MAYOR");
        mReportes.add(mRMayor);

        mRBalanza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mRBalanza.setText("BALANZA DE COMPROBACION");
        mReportes.add(mRBalanza);

        mREstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mREstado.setText("ESTADO DE RESULTADO");
        mReportes.add(mREstado);

        mRBalance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mRBalance.setText("BALANCE GENERAL");
        mReportes.add(mRBalance);

        jMenuBar1.add(mReportes);

        mEjercicio.setText("EJERCICIO");
        mEjercicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        mEApertura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mEApertura.setText("APERTURA");
        mEApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEAperturaActionPerformed(evt);
            }
        });
        mEjercicio.add(mEApertura);

        mECierre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mECierre.setText("CIERRE");
        mEjercicio.add(mECierre);

        jMenuBar1.add(mEjercicio);

        jMenu3.setText("SALIR");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jMenuItem13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem13.setText("CERRAR PROGRAMA");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCGestionActionPerformed
        // TODO add your handling code here:
        GestionCuentas vista = new GestionCuentas(escritorio);
        vista.setClosable(true);
        escritorio.add(vista);
        Dimension escritorioSize = escritorio.getSize();
        Dimension tamaño = vista.getSize();
        vista.setLocation((escritorioSize.width - tamaño.width) / 2, (escritorioSize.height - tamaño.height) / 2);
        vista.show();
    }//GEN-LAST:event_mCGestionActionPerformed

    private void mCIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCIngresarActionPerformed
        // TODO add your handling code here:
        RegistroCuentas vista = new RegistroCuentas(escritorio);
        vista.setClosable(true);
        escritorio.add(vista);
        Dimension escritorioSize = escritorio.getSize();
        Dimension tamaño = vista.getSize();
        vista.setLocation((escritorioSize.width - tamaño.width) / 2, (escritorioSize.height - tamaño.height) / 2);
        vista.show();
    }//GEN-LAST:event_mCIngresarActionPerformed

    private void mPIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPIngresarActionPerformed
        RegistroPartida vista = new RegistroPartida(escritorio);
        vista.setClosable(true);
        escritorio.add(vista);
        Dimension escritorioSize = escritorio.getSize();
        Dimension tamaño = vista.getSize();
        vista.setLocation((escritorioSize.width - tamaño.width) / 2, (escritorioSize.height - tamaño.height) / 2);
        vista.show();
    }//GEN-LAST:event_mPIngresarActionPerformed

    private void mEAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEAperturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mEAperturaActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "¿CERRAR PROGRAMA?", "CONFIRME", WIDTH);
        if(i==0){
        dispose();}
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem mCGestion;
    private javax.swing.JMenuItem mCIngresar;
    private javax.swing.JMenu mCuenta;
    private javax.swing.JMenuItem mEApertura;
    private javax.swing.JMenuItem mECierre;
    private javax.swing.JMenu mEjercicio;
    private javax.swing.JMenuItem mPIngresar;
    private javax.swing.JMenu mPartida;
    private javax.swing.JMenuItem mRBalance;
    private javax.swing.JMenuItem mRBalanza;
    private javax.swing.JMenuItem mRDiario;
    private javax.swing.JMenuItem mREstado;
    private javax.swing.JMenuItem mRMayor;
    private javax.swing.JMenu mReportes;
    // End of variables declaration//GEN-END:variables
}
