/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorCuenta;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import modelo.Cuenta;

/**
 *
 * @author jose
 */
public class RegistroCuentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroCuentas
     */
    JDesktopPane escritorio;
    String tipoSaldo;
    Integer nivel;
    ControladorCuenta controlador = new ControladorCuenta();

    public RegistroCuentas(JDesktopPane es) {
        initComponents();
        escritorio = es;
        controlador = new ControladorCuenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        rDeudor = new javax.swing.JRadioButton();
        rAcreedor = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Kalinga", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRO DE CUENTAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("Codigo:");

        textCodigo.setBackground(new java.awt.Color(108, 122, 137));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Tipo de Saldo:");

        textNombre.setBackground(new java.awt.Color(108, 122, 137));

        rDeudor.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(rDeudor);
        rDeudor.setForeground(new java.awt.Color(236, 240, 241));
        rDeudor.setText("Deudor");
        rDeudor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rDeudorActionPerformed(evt);
            }
        });

        rAcreedor.setBackground(new java.awt.Color(44, 62, 80));
        buttonGroup1.add(rAcreedor);
        rAcreedor.setForeground(new java.awt.Color(236, 240, 241));
        rAcreedor.setText("Acreedor");
        rAcreedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAcreedorActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(192, 57, 43));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonRegistrar.setBackground(new java.awt.Color(51, 153, 255));
        botonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rDeudor)
                            .addGap(18, 18, 18)
                            .addComponent(rAcreedor))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rDeudor)
                    .addComponent(rAcreedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:
        String nombre = textNombre.getText();
        String codigo = textCodigo.getText();
        String tipoSaldo = this.tipoSaldo;

        if (validar(nombre, codigo, tipoSaldo)) {
            if (controlador.Existe(codigo)) {
                JOptionPane.showMessageDialog(null, "Ya existe el codigo de esta cuenta");
            } else {
                int longitud = codigo.length();
                String codiaux = "";
                if (codigo.charAt(longitud - 1) == 'R') {
                    longitud = longitud - 1;
                }
                for (int ini = 0; ini < longitud; ini++) {
                    codiaux = codiaux + codigo.charAt(ini);
                }
                nivel = insertarNivel(longitud);
                JOptionPane.showMessageDialog(null, "" + nivel);
                if (nivel == null) {
                    JOptionPane.showMessageDialog(null, "Nivel invalido");
                } else {
                    Integer idOrden = generarOrden(codiaux, nivel);
                    if (idOrden == null) {
                        JOptionPane.showMessageDialog(null, "No concuerda con un nivel superior");
                    } else {
                        if (idOrden == 0) {
                            idOrden = null;
                        }
                        System.out.println("a ver");
                        longitud = longitud - 1;
                        if ((nivel >= 3 && codigo.charAt(longitud) == 'R') || (nivel < 3 && codigo.charAt(longitud) != 'R')) {
                            String tipocuenta = generarTipoCuenta(codigo);
                            Cuenta cuenta = new Cuenta(codigo, nombre, tipoSaldo, 0.0, idOrden, "", nivel, tipocuenta, "no");
                            // Cuenta cuenta = new Cuenta
                            controlador.AgregarCuenta(cuenta);
                            System.out.println("simon");
                        } else {
                            JOptionPane.showMessageDialog(null, "Para poseer R la cuenta debe de ser nivel 3 o superior");
                        }

                    }
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Complete campos");
        }
        //        ControladorCuenta aux = new ControladorCuenta();

    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void rDeudorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rDeudorActionPerformed
        // TODO add your handling code here:
        tipoSaldo = rDeudor.getText();
    }//GEN-LAST:event_rDeudorActionPerformed

    private void rAcreedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAcreedorActionPerformed
        // TODO add your handling code here:
        tipoSaldo = rAcreedor.getText();
    }//GEN-LAST:event_rAcreedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rAcreedor;
    private javax.swing.JRadioButton rDeudor;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables

    private Integer insertarNivel(int nivel) {

        if (nivel == 1 || nivel == 2) {
            return nivel;
        } else if (nivel == 4) {
            return 3;
        } else if (nivel == 6) {
            return 4;
        } else if (nivel == 8) {
            return 5;
        } else if (nivel == 10) {
            return 6;
        }
        return null;

    }

    private Integer generarOrden(String codigo, Integer nivel) {

        String aux = "";
        Integer auxi = 0;
        Boolean bandera = false;
        if (nivel == 1) {
            return 0;
        } else {
            if (nivel == 2) {
                auxi = 1;
            } else {
                auxi = codigo.length() - 2;
            }
            for (int i = 0; i < auxi; i++) {
                aux = aux + codigo.charAt(i);
            }
            auxi = Integer.parseInt(aux);
            bandera = controlador.Verificar(auxi);
            if (bandera == true) {
                Integer idcuenta = controlador.obtenerId(auxi);
                return idcuenta;
            } else {
                return null;
            }
        }
    }

    private boolean validar(String nombre, String codigo, String tipoSaldo) {
        if (nombre.equals("")) {
            return false;
        }
        if (codigo.equals("")) {
            return false;
        }
        if (tipoSaldo.equals("")) {
            return false;
        }
        return true;
    }

    private String generarTipoCuenta(String codigo) {
        String aux = "";
        if (codigo.charAt(0) == '1') {
            aux = "ACTIVO";
        } else if (codigo.charAt(0) == '2') {
            aux = "PASIVO";
        } else if (codigo.charAt(0) == '3') {
            aux = "PATRIMONIO";
        } else if (codigo.charAt(0) == '4') {
            aux = "INGRESOS";
        } else if (codigo.charAt(0) == '5') {
            aux = "COSTOS";
        } else if (codigo.charAt(0) == '6') {
            aux = "GASTOS";
        } else if (codigo.charAt(0) == '7') {
            aux = "CUENTAS DE CONTROL";
        } else if (codigo.charAt(0) == '8') {
            aux = "CUNETAS DE ORDEN";
        }
        return aux;
    }

}
