/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.*;

/**
 *
 * @author Pérez
 */
public class RegistroPartida extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroPartida
     */
    JDesktopPane escritorio;
    DecimalFormat df = new DecimalFormat("0.00");
    SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    ControladorPartida cp;
    ControladorTransaccion ct;
    Partida pda;
    Transaccion trn;
    String elmt = "", cd = "";
    DefaultTableModel modelo;
    int cr = 0;
    ArrayList<Transaccion> tran;

    public RegistroPartida(JDesktopPane es) {
        initComponents();
        this.resizable = false;
        escritorio = es;
        cp = new ControladorPartida();
        ct = new ControladorTransaccion();
        pda = new Partida();
        modelo();
        tabla.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Ver(e); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }

    public void modelo() {
        modelo = new DefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("CUENTA");
        modelo.addColumn("DEBE");
        modelo.addColumn("HABER");
        tabla.setModel(modelo);
    }

    private void Ver(MouseEvent e) {
        cd = String.valueOf(tabla.rowAtPoint(e.getPoint()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmenu = new javax.swing.JPopupMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tnpartida = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfecha = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        tCuenta = new javax.swing.JTextField();
        bNueva = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nCuenta = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tMonto = new javax.swing.JTextField();
        tColumna = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        civa = new javax.swing.JComboBox<>();
        tiva = new javax.swing.JComboBox<>();
        pm = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        bEliminar = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        tdebe = new javax.swing.JLabel();
        thaber = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tConcepto = new javax.swing.JTextArea();

        jPanel2.setBackground(new java.awt.Color(248, 148, 6));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Kalinga", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AGREGAR PARTIDA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PARTIDA #");

        tnpartida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("FECHA");

        tfecha.setDateFormatString("dd-MM-yyyy");
        tfecha.setEnabled(false);
        tfecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("CUENTA #");

        tCuenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tCuenta.setToolTipText("PRESIONE ENTER PARA ESTABLECER CUENTA");
        tCuenta.setEnabled(false);
        tCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tCuentaFocusLost(evt);
            }
        });
        tCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tCuentaKeyTyped(evt);
            }
        });

        bNueva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bNueva.setText("NUEVA PARTIDA");
        bNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevaActionPerformed(evt);
            }
        });

        bAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bAgregar.setText("AGREGAR");
        bAgregar.setEnabled(false);
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("CUENTA");

        nCuenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nCuenta.setEnabled(false);
        nCuenta.setFocusable(false);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("TRANSACCION"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("MONTO");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("COLUMNA");

        tMonto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tMonto.setEnabled(false);
        tMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tMontoKeyTyped(evt);
            }
        });

        tColumna.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tColumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "DEBE", "HABER" }));
        tColumna.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tMonto)
                    .addComponent(tColumna, 0, 145, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("IVA"));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("TIPO");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("CALCULO");

        civa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        civa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "INCLUIDO", "NO INCLUIDO" }));
        civa.setEnabled(false);
        civa.setFocusable(false);

        tiva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tiva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIN IVA", "CREDITO FISCAL", "DEBITO FISCAL" }));
        tiva.setEnabled(false);
        tiva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tivaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(civa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tiva, 0, 145, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(civa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pmLayout = new javax.swing.GroupLayout(pm);
        pm.setLayout(pmLayout);
        pmLayout.setHorizontalGroup(
            pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        pmLayout.setVerticalGroup(
            pmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(tnpartida, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(tfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(tCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(nCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bNueva)
                    .addComponent(bAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tnpartida, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(bNueva)
                        .addGap(11, 11, 11)
                        .addComponent(bAgregar))))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("ACCIONES"));

        bEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bEliminar.setText("ELIMINAR FILA");
        bEliminar.setEnabled(false);
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bGuardar.setText("GUARDAR");
        bGuardar.setEnabled(false);
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bLimpiar.setText("LIMPIAR");
        bLimpiar.setEnabled(false);
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        bSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bSalir.setText("SALIR");
        bSalir.setEnabled(false);
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bEliminar)
                .addGap(21, 21, 21)
                .addComponent(bGuardar)
                .addGap(21, 21, 21)
                .addComponent(bLimpiar)
                .addGap(21, 21, 21)
                .addComponent(bSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "CUENTA", "DEBE", "HABER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("TOTALES:");

        tdebe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tdebe.setText("DEBE");

        thaber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thaber.setText("HABER");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("CONCEPTO");

        tConcepto.setColumns(20);
        tConcepto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tConcepto.setRows(5);
        tConcepto.setEnabled(false);
        jScrollPane2.setViewportView(tConcepto);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tdebe, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thaber, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tdebe)
                            .addComponent(thaber))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevaActionPerformed
        acciones(1, true);
        tCuenta.requestFocus();
        numP();
        pda = new Partida();
        pda.setNumpartida(Integer.parseInt(tnpartida.getText()));
        tran = new ArrayList();
        JOptionPane.showMessageDialog(rootPane, "SOLO CUENTAS DE NIVEL 3 PUEDEN SER PARTE DE LAS "
                + "TRANSACCIONES", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bNuevaActionPerformed

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        if (validarA()) {
            int idcta = Integer.parseInt(tCuenta.getText());
            double mt = Double.parseDouble(tMonto.getText());
            int op = tColumna.getSelectedIndex();
            trn = new Transaccion(pda.getIdpartida(), idcta, mt, op);
            agrtab(trn, 0);
            agriva();
            acciones(3, true);
            tCuenta.requestFocus();
        }
    }//GEN-LAST:event_bAgregarActionPerformed

    private void tivaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tivaItemStateChanged
        int pos = tiva.getSelectedIndex();
        switch (pos) {
            case 0:
                civa.setEnabled(false);
                civa.setSelectedIndex(0);
                break;
            default:
                civa.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_tivaItemStateChanged

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        if (cd != "") {
            modelo.removeRow(Integer.parseInt(cd));//ELIMINA DE LA TABLA
            cr--;//BAJA EL INDICIE USADO COMO REFERENCIA DE LAS FILAS EN LA TABLA
            tran.remove(Integer.parseInt(cd));//BORRA LA TRANSACCION DEL ARREGLO
            totales();//ACTUALIZA LOS TOTALES
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        if (validarB()) {
            Date f = tfecha.getDate();
            Timestamp fts  = new Timestamp(f.getTime());
            pda.setFecha(fts);
            String cnc = tConcepto.getText();
            pda.setConcepto(cnc);
            boolean bb = cp.agregarPartida(pda);
            Transaccion trt = null;
            for (int i = 0; i < tran.size(); i++) {
                trt = tran.get(i);
                trt.setIdpartida(cp.idpart(pda));
                ct.AgregarTransaccion(trt);
            }
            if(bb)
            acciones(4, false);
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        acciones(2, true);
        tCuenta.requestFocus();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void tCuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tCuentaFocusLost

    }//GEN-LAST:event_tCuentaFocusLost

    private void tMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tMontoKeyTyped
        char caracter = evt.getKeyChar();
        boolean bo = false;
        for (int i = 0; i < tMonto.getText().length(); i++) {
            if (tMonto.getText().charAt(i) == '.') {
                bo = true;
            }
        }
        if ((caracter < '0' || caracter > '9') && caracter != '\b' && caracter != '.') {
            evt.consume();  // ignorar el evento de teclado
        }
        if (bo && caracter == '.') {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_tMontoKeyTyped

    private void tCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCuentaKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9' && caracter != '\b') {
            evt.consume();
        }
        if (evt.getKeyChar() != KeyEvent.VK_ENTER) {
            nCuenta.setText("");
            pmenu.removeAll();
            bus(tCuenta.getText());
            if ((evt.getKeyChar() > '0' || evt.getKeyChar() < '9')) {
                pmenu.setVisible(false);
                if (elmt != null) {
                    pmenu.show(pm, evt.getKeyLocation(), evt.getKeyLocation());
                    pmenu.setVisible(true);
                    tCuenta.requestFocus();
                }
            }
            if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) {
                pmenu.setVisible(false);
                if (elmt != null) {
                    pmenu.show(pm, evt.getKeyLocation(), evt.getKeyLocation());
                    pmenu.setVisible(true);
                    tCuenta.requestFocus();
                }
            }
        } else {
            if (cexiste(tCuenta.getText()) != "") {
                if(tCuenta.getText().length() > 3){
                nCuenta.setText(cexiste(tCuenta.getText()));
                if ("1107".equals(tCuenta.getText()) || "2105".equals(tCuenta.getText())) {
                        tiva.setEnabled(false);
                    } else {
                        tiva.setEnabled(true);
                    }
                }else{
                JOptionPane.showMessageDialog(rootPane, "SOLO CUENTAS DE NIVEL 3 PUEDEN SER PARTE DE LAS "
                + "TRANSACCIONES", "INFORMACION", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                nCuenta.setText("");
            }
        }
    }//GEN-LAST:event_tCuentaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bNueva;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> civa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nCuenta;
    private javax.swing.JPanel pm;
    private javax.swing.JPopupMenu pmenu;
    private javax.swing.JComboBox<String> tColumna;
    private javax.swing.JTextArea tConcepto;
    private javax.swing.JTextField tCuenta;
    private javax.swing.JTextField tMonto;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel tdebe;
    private com.toedter.calendar.JDateChooser tfecha;
    private javax.swing.JLabel thaber;
    private javax.swing.JComboBox<String> tiva;
    private javax.swing.JLabel tnpartida;
    // End of variables declaration//GEN-END:variables

    private void acciones(int i, boolean b) {
        bAgregar.setEnabled(b);
        bEliminar.setEnabled(b);
        bGuardar.setEnabled(b);
        bLimpiar.setEnabled(b);
        bSalir.setEnabled(b);
        tfecha.setEnabled(b);
        tfecha.setDate(new Date());
        tCuenta.setEnabled(b);
        nCuenta.setEnabled(b);
        tMonto.setEnabled(b);
        tColumna.setEnabled(b);
        tiva.setEnabled(b);
        tConcepto.setEnabled(b);
        bNueva.setEnabled(!b);
        if (i == 2 || i == 3 || i == 4) {
            tCuenta.setText("");
            nCuenta.setText("");
            tMonto.setText("");
            tColumna.setSelectedIndex(0);
            tiva.setSelectedIndex(0);
            civa.setSelectedIndex(0);
            if (i == 2 || i == 4) {
                tConcepto.setText("");
                tdebe.setText("DEBE");
                thaber.setText("HABER");
                modelo();
                if (i == 4) {
                    tnpartida.setText("");
                    tfecha.setDate(null);
                }
                cr = 0;
            }
        }
    }

    private void numP() {
        pda = cp.numeroPartida();
        if (pda == null) {
            tnpartida.setText("1");
        } else {
            tnpartida.setText("" + (pda.getNumpartida() + 1));
        }
    }

    private boolean validarA() {
        boolean b = false;
        if (tnpartida.getText() == "" || tMonto.getText() == "" || tColumna.getSelectedIndex() == 0
                || (tiva.getSelectedIndex() != 0 && civa.getSelectedIndex() == 0)) {
            b = false;
            JOptionPane.showMessageDialog(rootPane, "COMPLETE/SELECCIONE LOS CAMPOS CORRESPONDIENTES", "FALTAN DATOS", HEIGHT);
        } else {
            b = true;
        }
        return b;
    }

    private boolean validarB() {
        if (thaber.getText().equals(tdebe.getText()) && !tConcepto.getText().equals("")) {
            return true;
        } else if (!thaber.getText().equals(tdebe.getText())) {
            JOptionPane.showMessageDialog(rootPane, "EL DEBE Y EL HABER NO CUADRAN", "NO CUADRA", JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            JOptionPane.showMessageDialog(rootPane, "INGRESE EL CONCEPTO DE LA PARTIDA", "INGRESE DATO", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }

    //PARA MENU POPUP DE CODIGO DE CUENTAS
    private void bus(String c) {
        if (c.length() > 1) {
            Conexion conexion = new Conexion();
            Statement st = null;
            ResultSet rs = null;
            try {
                st = conexion.abrirConexion().createStatement();
                rs = st.executeQuery("SELECT codigo, nombre "
                        + "FROM cuenta WHERE codigo LIKE '" + c + "%'");
                while (rs.next()) {
                    elmt = rs.getString("codigo") + " | " + conexion.resultado.getString("nombre");
                    JMenuItem p = new JMenuItem(elmt);
                    p.setEnabled(false);
                    pmenu.add(p);
                }
                conexion.cerrarConexion();
            } catch (Exception e) {
                System.out.println("ERROR" + e.getMessage());
            }
        }
    }

    //RELLENAR EL NOMBRE DE CUENTA SI EL CODIGO ES VALIDO
    private String cexiste(String c) {
        Conexion conexion = new Conexion();
        Statement st = null;
        ResultSet rs = null;
        String b = "";
        try {
            st = conexion.abrirConexion().createStatement();
            rs = st.executeQuery("SELECT nombre FROM cuenta WHERE codigo = " + c);
            rs.beforeFirst();
            while (rs.next()) {
                b = rs.getString("nombre");
            }
            conexion.cerrarConexion();
        } catch (Exception e) {
            System.out.println("ERROR" + e.getMessage());
        }
        return b;
    }

    private void agrtab(Transaccion tra, int bnx) {
        modelo.setRowCount(cr + 1);
        modelo.setValueAt(tra.getIdcuenta(), cr, 0);
        modelo.setValueAt(cexiste(String.valueOf(tra.getIdcuenta())), cr, 1);
        for (int i = 0; i <= 2; i++) {
            if (i == tra.getOperacion()) {
                modelo.setValueAt(df.format(tra.getMonto()), cr, i + 1);
                if (bnx == 1) {
                    double val = Double.parseDouble((String) modelo.getValueAt(cr - 1, i + 1)) - tra.getMonto();
                    modelo.setValueAt(df.format(val), cr - 1, i + 1);
                    tran.get(cr - 1).setMonto(val);
                }
            } else {
                if (i != 0) {
                    modelo.setValueAt(0.00, cr, i + 1);
                }
            }
        }
        int idc = new ControladorCuenta().obtenerId(tra.getIdcuenta());
        System.out.println("id "+idc);
        tra.setIdcuenta(idc);
        tran.add(tra);
        cr++;
        totales();
    }

    private void agriva() {
        int tipo = tiva.getSelectedIndex();
        if (tipo > 0) {
            int cod = 0;
            String cta = "";
            double monto = Double.parseDouble(tMonto.getText());
            int calc = civa.getSelectedIndex();
            double ivan = monto * 0.13;
            monto = monto / 1.13;
            double ivai = monto * 0.13;
            switch (tipo) {
                case 1://CREDITO
                    cod = 1107;
                    cta = "IVA CREDITO FISCAL";
                    if (calc == 1) {//INCLUIDO
                        trn = new Transaccion(pda.getNumpartida(), cod, ivai, tColumna.getSelectedIndex());
                        cod = 1;
                    } else if (calc == 2) {//NO INCLUIDO
                        trn = new Transaccion(pda.getNumpartida(), cod, ivan, tColumna.getSelectedIndex());
                        cod = 0;
                    }
                    break;
                case 2://DEBITO
                    cod = 2105;
                    cta = "IVA DEDITO FISCAL";
                    if (calc == 1) {//INCLUIDO
                        trn = new Transaccion(pda.getNumpartida(), cod, ivai, tColumna.getSelectedIndex());
                        cod = 1;
                    } else if (calc == 2) {//NO INCLUIDO
                        trn = new Transaccion(pda.getNumpartida(), cod, ivan, tColumna.getSelectedIndex());
                        cod = 0;
                    }
                    break;
            }
            agrtab(trn, cod);
        }
    }

    private void totales() {
        double debe = 0;
        double haber = 0;
        for (int i = 0; i < cr; i++) {
            debe += Double.parseDouble(modelo.getValueAt(i, 2).toString());
            haber += Double.parseDouble(modelo.getValueAt(i, 3).toString());
        }
        tdebe.setText(df.format(debe));
        thaber.setText(df.format(haber));
    }
}
